### PR TITLE
fix: prevents exception on construction of `FunctionConverter` with duplicate functions

### LINKED ISSUE #562: `FunctionConverter` crashes when multiple extensions define functions with the same name and signature
When merging extension collections that contain functions with identical names and signatures but different URNs, `FunctionConverter` throws `IllegalArgumentException` during initialization. This prevents using multiple extension sets that reasonably might implement the same function (e.g., ltrim) with slightly different semantics or optimizations.

Example Error:
```
java.lang.IllegalArgumentException: Multiple entries with same key: ltrim:str_str
    at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:...)
    at io.substrait.isthmus.expression.FunctionConverter$FunctionFinder.<init (FunctionConverter.java:179)
```

### PR DESCRIPTION
**Pull request by benbellick**
Closes #562 

This test resolves an issue in which `FunctionConverter`s constructed with `ExtensionCollection`s that contain multiple functions with different URNs results in an exception being thrown. 

The fix is to allow a list of functions to be associated with a particular `<name>:<sig>` pairing, and then to select the final option of those available. This is reflected in the comments, which clarify that the last added function takes precedence.

### CODE REVIEW

File: isthmus/src/main/java/io/substrait/isthmus/expression/FunctionConverter.java [hunk 1]
```diff
@@ -75,9 +76,9 @@ public FunctionConverter(
     this.typeFactory = typeFactory;
     this.substraitFuncKeyToSqlOperatorMap = ArrayListMultimap.create();
 
-    ArrayListMultimap<String, F> alm = ArrayListMultimap.<String, F>create();
+    ArrayListMultimap<String, F> nameToFn = ArrayListMultimap.<String, F>create();
```
Comment (benbellick) [inline isthmus/src/main/java/io/substrait/isthmus/expression/FunctionConverter.java:122]: This is unrelated to the PR technically, but I just thought that this was a clearer name.

File: isthmus/src/test/java/io/substrait/isthmus/DuplicateFunctionUrnTest.java [hunk 2]
```diff
@@ -0,0 +1,127 @@
...
+      }
+
+      String urn1 = ltrimFunctions.get(0).getAnchor().urn();
+      String urn2 = ltrimFunctions.get(1).getAnchor().urn();
+      if (urn1.equals(urn2)) {
+        throw new IllegalStateException(
+            "Expected different URNs for the two ltrim functions, but both were: " + urn1);
+      }
+    } catch (IOException e) {
+      throw new RuntimeException(e);
```
Comment (nielspardon) [inline isthmus/src/test/java/io/substrait/isthmus/DuplicateFunctionUrnTest.java]: FYI: there is `UncheckedIOException` specifically for this purpose which avoids throwing a raw exception type:
```suggestion
      throw new UncheckedIOException(e);
```
https://docs.oracle.com/javase/8/docs/api/java/io/UncheckedIOException.html

Comment (benbellick) [reply isthmus/src/test/java/io/substrait/isthmus/DuplicateFunctionUrnTest.java]: Thanks! Just added that.

File: isthmus/src/test/java/io/substrait/isthmus/DuplicateFunctionUrnTest.java [hunk 3]
```diff
@@ -0,0 +1,187 @@
...
+  static final SimpleExtension.ExtensionCollection collection1;
+  static final SimpleExtension.ExtensionCollection collection2;
+  static final SimpleExtension.ExtensionCollection collection;
+
+  static {
+    try {
+      String extensions1 = asString("extensions/functions_duplicate_urn1.yaml");
+      String extensions2 = asString("extensions/functions_duplicate_urn2.yaml");
+      collection1 = SimpleExtension.load("urn1://functions", extensions1);
+      collection2 = SimpleExtension.load("urn2://functions", extensions2);
```
Comment (nielspardon) [inline isthmus/src/test/java/io/substrait/isthmus/DuplicateFunctionUrnTest.java]: I think given that URNs are valid URIs you could provide URNs here as the URI for consistency:

```suggestion
      collection1 = SimpleExtension.load("urn:extension:io.substrait:functions_string", extensions1);
      collection2 = SimpleExtension.load("urn:extension:com.domain:string", extensions2);
```

File: isthmus/src/main/java/io/substrait/isthmus/expression/FunctionConverter.java [hunk 4]
```diff
@@ -349,6 +350,9 @@ public Optional<T> attemptMatch(C call, Function<RexNode, Expression> topLevelCo
        * Not enough context here to construct a substrait EnumArg.
        * Once a FunctionVariant is resolved we can map the String Literal
        * to a EnumArg.
+       *
+       * Note that if there are multiple registered function extensions which can match a particular Call,
+       * the last one added to the extension collection will be matched.
```
Comment (nielspardon) [inline isthmus/src/main/java/io/substrait/isthmus/expression/FunctionConverter.java:422]: I'm wondering whether this comment should be also in a more prominent place for any consumers of isthmus and where they would find that. Would maybe at the top of the `FunctionConverter` class be more prominent?

File: isthmus/src/test/java/io/substrait/isthmus/DuplicateFunctionUrnTest.java [hunk 5]
```diff
@@ -0,0 +1,187 @@
...
+import java.util.Optional;
+import org.apache.calcite.rex.RexBuilder;
+import org.apache.calcite.rex.RexCall;
+import org.apache.calcite.rex.RexNode;
+import org.apache.calcite.sql.fun.SqlStdOperatorTable;
+import org.apache.calcite.sql.fun.SqlTrimFunction.Flag;
+import org.junit.jupiter.api.Test;
+
+/** Tests to reproduce #562 */
+public class DuplicateFunctionUrnTest extends PlanTestBase {
```
Comment (nielspardon) [inline isthmus/src/test/java/io/substrait/isthmus/DuplicateFunctionUrnTest.java]: I think for JUnit 5 the test class can be package private:

```suggestion
class DuplicateFunctionUrnTest extends PlanTestBase {
```

File: isthmus/src/test/java/io/substrait/isthmus/DuplicateFunctionUrnTest.java [hunk 6]
```diff
@@ -0,0 +1,187 @@
...
+
+    assertNotNull(converter);
+  }
+
+  @Test
+  void testDuplicateWindowFunctionWithDifferentUrns() {
+    WindowFunctionConverter converter =
+        new WindowFunctionConverter(collection.windowFunctions(), typeFactory);
+
+    assertNotNull(converter);
```
Comment (nielspardon) [inline isthmus/src/test/java/io/substrait/isthmus/DuplicateFunctionUrnTest.java]: interesting, is it really possible that a constructor returns null in Java?

**Comment by nielspardon** [comment]
looks good in general. just some minor remarks from my side

File: isthmus/src/test/java/io/substrait/isthmus/DuplicateFunctionUrnTest.java (hunk 3 above)
Comment (benbellick) [reply isthmus/src/test/java/io/substrait/isthmus/DuplicateFunctionUrnTest.java]: Yeah that is probably a bit easier to read

File: isthmus/src/test/java/io/substrait/isthmus/DuplicateFunctionUrnTest.java (hunk 6 above)
Comment (benbellick) [reply isthmus/src/test/java/io/substrait/isthmus/DuplicateFunctionUrnTest.java]: Good point!

Comment (benbellick) [reply isthmus/src/test/java/io/substrait/isthmus/DuplicateFunctionUrnTest.java]: So I had to actually use these values somewhere so that the linter doesn't complain. I ended up just wrapping the construction of these objects in `assertDoesNotThrow`.

File: isthmus/src/main/java/io/substrait/isthmus/expression/FunctionConverter.java (hunk 4 above)
Comment (benbellick) [reply isthmus/src/main/java/io/substrait/isthmus/expression/FunctionConverter.java:422]: I ended up adding quite a bit of comments. Let me know if anything added is incorrect or just too much :)

File: isthmus/src/main/java/io/substrait/isthmus/expression/FunctionConverter.java [hunk 7]
```diff
@@ -112,6 +156,17 @@ public FunctionConverter(
...
+   * Converts a Substrait function to a Calcite SqlOperator (Substrait → Calcite direction).
+   *
+   * <p>Given a Substrait function key (e.g., "concat:str_str") and output type, this method finds
+   * the corresponding Calcite SqlOperator. When multiple operators match, the output type is used
+   * to disambiguate.
+   *
+   * @param key the Substrait function key (function name with type signature)
+   * @param outputType the expected output type
+   * @return the matching SqlOperator, or empty if no match found
+   */
```
Comment (nielspardon) [inline isthmus/src/main/java/io/substrait/isthmus/expression/FunctionConverter.java:169]: not a must, I tend to add `{@link xxx}` to mentions of classes/methods hoping they might be useful for a reader of the javadocs

```suggestion
  /**
   * Converts a Substrait function to a Calcite {@link SqlOperator} (Substrait → Calcite direction).
   *
   * <p>Given a Substrait function key (e.g., "concat:str_str") and output type, this method finds
   * the corresponding Calcite {@link SqlOperator}. When multiple operators match, the output type is used
   * to disambiguate.
   *
   * @param key the Substrait function key (function name with type signature)
   * @param outputType the expected output type
   * @return the matching {@link SqlOperator}, or empty if no match found
   */
```

File: isthmus/src/main/java/io/substrait/isthmus/expression/FunctionConverter.java (hunk 4 above)
Comment (nielspardon) [reply isthmus/src/main/java/io/substrait/isthmus/expression/FunctionConverter.java:422]: looks great, I was suggesting to Victor a couple weeks in another PR that we maybe should try to add javadocs whenever we touch code to slowly build up javadoc documentation so this is a great contribution

**Review by nielspardon — APPROVED** [review]
LGTM

File: isthmus/src/main/java/io/substrait/isthmus/expression/FunctionConverter.java (hunk 7 above)
Comment (benbellick) [reply isthmus/src/main/java/io/substrait/isthmus/expression/FunctionConverter.java:169]: That was a good idea, just pushed a commit for it.
