### PR TITLE
fix(isthmus): correct strpos parameter order

### LINKED ISSUE #662: STRPOS and POSITION
The subtrait function strpos was mapped to calcite's POSITION function in this [PR](https://github.com/substrait-io/substrait-java/pull/610/files).

I believe the two are not one to one mappings of one another as the semantics agruments are swapped. Substrait describes [strpos](https://github.com/substrait-io/substrait/blob/92d2e757a330f9c973bb566817dc92afd1badcb2/extensions/functions_string.yaml#L609), as the second arugment being the substring, while [calcite's position](https://github.com/apache/calcite/blob/35768a76e71eb2b8c1150494b7cd53af77c40574/core/src/main/java/net/hydromatic/optiq/runtime/SqlFunctions.java#L958), has the first argument being the substring.

### PR DESCRIPTION
**Pull request by bestbeforetoday**
Both SQL STRPOS and POSITION functions are modelled by Calcite as Position. Parameters are substring followed by the input to be searched. This maps to the Substrait strpos function, which has the parameters of input to be searched followed by substring. The default mapping retains the argument order, which results in SQL being translated to incorrect Substrait, and correct Substrait translated to incorrect SQL. Round-trip between Substrait and SQL still works since the parameter order is reversed in both directions, resulting in the correct order again.

This change adds a custom function mapper to reverse the order of the first two parameters when converting between Calcite Position and Substrait strpos functions.

Closes #662

### CODE REVIEW

File: isthmus/src/main/java/io/substrait/isthmus/expression/PositionFunctionMapper.java [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+  }
+
+  @Override
+  public Optional<SubstraitFunctionMapping> toSubstrait(final RexCall call) {
+    if (!SqlStdOperatorTable.POSITION.equals(call.op)) {
+      return Optional.empty();
+    }
+
+    List<RexNode> operands = new ArrayList<>(call.getOperands());
+    Collections.swap(operands, 0, 1);
```
Comment (benbellick) [inline isthmus/src/main/java/io/substrait/isthmus/expression/PositionFunctionMapper.java:43]: Probably not a bad idea to put a comment here just because we have some naked numbers used to reference parameters.

File: isthmus/src/test/java/io/substrait/isthmus/StringFunctionTest.java [hunk 2]
```diff
@@ -227,87 +225,95 @@ void testContains(String left, String right) throws Exception {
...
+      value = {"vc, 'substring'", "'string', vc"},
       quoteCharacter = '`')
-  void testStrposWithLiteral(String left, String right) throws Exception {
+  void testStrposWithLiteral(String input, String substring) throws Exception {
+    String query = String.format("SELECT STRPOS(%s, %s) FROM strings", input, substring);
+    assertSqlRoundTrip(query);
+  }
 
-    String query = String.format("SELECT STRPOS(%s, %s) > 0 FROM strings", left, right);
+  @Test
```
Comment (benbellick) [inline isthmus/src/test/java/io/substrait/isthmus/StringFunctionTest.java:264]:
```suggestion
  @Test
  // Verifies POSITION→strpos parameter swap (#662).
  // SQL POSITION(substring IN input) must become Substrait strpos(input, substring).
```

Just so someone has a reference for the future :)

File: isthmus/src/main/java/io/substrait/isthmus/expression/PositionFunctionMapper.java (hunk 1 above)
Comment (bestbeforetoday) [reply isthmus/src/main/java/io/substrait/isthmus/expression/PositionFunctionMapper.java:43]: Is the class Javadoc not sufficient?

Comment (benbellick) [reply isthmus/src/main/java/io/substrait/isthmus/expression/PositionFunctionMapper.java:43]: It's probably fine, just my opinion if we wanted to make it extra clear. Feel free to ignore if you disagree.

**Comment by benbellick** [comment]
@bestbeforetoday sorry, I'm not sure I am able to see those comment changes? 

Also, very small thing, but since we squash merge in this repo anyways, I think it is better to always do changes in new commits rather than force-pushing. This way, I can view the diff of what changed just from when I last viewed. Thanks! 🙂
